[language-server.pyright]
command = "stuff-pyright"
args = ["--stdio"]
config = {}

[language-server.pylsp]
command = "stuff-pylsp"
config = {}

[language-server.ember]
command = "ember-language-server"
args = ["--stdio"]
config = {}

[language-server.tailwindcss]
command = "tailwindcss-language-server"
args = ["--stdio"]
config = {}

[language-server.emmet]
args = ["--stdio"]
command="emmet-ls"

[[language]]
name = "python"
roots = ["pyproject.toml"]
language-servers = ["pylsp"]
# language-servers = [ { name = "pylsp", only-features = ["goto-definition", "goto-declaration", "goto-reference", "goto-implementation", "completion"] }, "pyright"]
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "handlebars"
injection-regex = "hbs"
roots = ["package.json"]
file-types = ["hbs"]
grammar = "glimmer"
language-servers = ["ember", "emmet"]
scope = "source.glimmer"


[[grammar]]
name = "glimmer"
source = { git = "https://github.com/alexlafroscia/tree-sitter-glimmer", rev = "d3031a8294bf331600d5046b1d14e690a0d8ba0c"}

[[grammar]]
name = "javascript"
source = { git = "https://github.com/tree-sitter/tree-sitter-javascript", rev= "3dac6b0f6ab659d37fa9f10ab415a59fe2d0dbad" }

[[language]]
name = "javascript"
language-servers = ["typescript-language-server"]
auto-format = true

[[language]]
name = "jsx"
roots = ["src/", "App.jsx", "package.json"]
language-servers = ["typescript-language-server", "emmet"]
auto-format = true

[[language]]
name = "gjs"
scope = "source.gjs"
file-types = ["gjs"]
roots = ["package.json", "ember-cli-build.js"]
language-servers = ["ember", "typescript-language-server"]
grammar = "javascript"

[[language]]
name = "gts"
scope = "source.gts"
file-types = ["gts"]
roots = ["package.json", "ember-cli-build.js"]
language-servers = ["ember", "typescript-language-server"]
grammar = "typescript"

# [[language]]
# name = "gjs"
# file-types = ["gjs"]
# roots = ["package.json", "ember-cli-build.js"]
# language-servers = ["ember"]
# auto-format = true
# grammar = "javascript"
# scope = "source.js"

[[language]]
name = "css"
formatter = { command = "prettier", args = ["--parser", "css"] }
auto-format = true