# Configuration for Alacritty, the GPU enhanced terminal emulator.

# Import additional configuration files
#
# Imports are loaded in order, skipping all missing files, with the importing
# file being loaded last. If a field is already present in a previous import, it
# will be replaced.
#
# All imports must either be absolute paths starting with `/`, or paths relative
# to the user's home directory starting with `~/`.
#import:
#  - /path/to/alacritty.yml
# Any items in the `env` entry below will be added as
# environment variables. Some entries may override variables
# set by alacritty itself.
#env:
# TERM variable
#
# This value is used to set the `$TERM` environment variable for
# each instance of Alacritty. If it is not present, alacritty will
# check the local terminfo database and use `alacritty` if it is
# available, otherwise `xterm-256color` is used.
#TERM: alacritty
colors:
  # Default colors
  primary:
    background: '#2E3440' 
    foreground: '#D8DEE9'

  # Normal colors
  normal:
    black: '#1D202F'
    red: '#BF616A'
    green: '#9ECE6A'
    yellow: '#EBCB8B'
    blue: '#7AA2F7'
    magenta: '#BB9AF7'
    cyan: '#7DCFFF'
    white: '#A9B1D6'

  indexed_colors:
    - { index: 16, color: '0xff9e64' }
    - { index: 17, color: '0xdb4b4b' }

# Font configuration
draw_bold_text_with_bright_colors: false
font:
  normal:
    family: Droid Sans Mono

  size: 12.0

window:
  decorations: full
  padding:
    x: 15
    y: 15
  title: Terminal
  opacity: 0.8
